### PR TITLE
feat: lambda authorizer added to api gateway

### PR DESCRIPTION
**Pull request by cshio**
lambdas updated

### CODE REVIEW

**Comment by kwjolee** [comment]
The Dynamo table name in `getParams` for `addUser` lambda seems to still be hardcoded.

Do we need to return the `context` object in the `authorizer` lambda? The AWS docs say it's optional and we don't appear to be using it in our system.

**Comment by cshio** [comment]
Thanks, I missed the second table name.

I removed `context` from `authorizer` and it works fine.

**Comment by cshio** [comment]
Added `authorizer_websocket`.  Can be attached as an authorizer to a WebSocket API `$connect` route.  Will check if the `userHash` submitted as query parameters exists in the `notification-users` database.  Currently does a full table scan.  Will research if using a table that is indexed from `userHash` to `id` will be more efficient.

`hash` column renamed to `userHash` in `notification-users` since it's a reserved keyword in DynamoDB.

**Comment by kwjolee** [comment]
Is `authorizer_websocket.mjs` compiled from a `ts` file? If so, it should be included here so we can migrate to CDK later. If not, this is tested and ready for merge.

**Comment by cshio** [comment]
It was written as is.  I'll redo it in TS later.

**Pull request merged**
